// <auto-generated />
namespace Portal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class department_nodenum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(department_nodenum));
        
        string IMigrationMetadata.Id
        {
            get { return "201703300659089_department_nodenum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
